### ISSUE TITLE
Cannot change registered server file locations

### ISSUE THREAD

**Issue by Zyferus** [micah686/SatisfactoryServerGUI#6]
When I first ran the app, I accidentally picked the incorrect folder for my server install. Now I cannot manage my server with the app, nor can I change the registered location to get it to properly manage my server.

There is a frustrating lack of documentation and modification for the app settings available.

**Comment by micah686** [comment]
Sorry about that. It was a fairly quick app I whipped up, but I haven't done any maintenance on it for a while. I'll see if I can get something updated on it.

**Comment by micah686** [comment]
@Zyferus 
Can you try this, and see if your issues are resolved?
https://github.com/micah686/SatisfactoryServerGUI/releases/tag/1.1.4

**Comment by micah686** [comment]
Closing as no response has been provided. @Zyferus , if you still encounter this issue, feel free to reopen the issue.
